openapi: "3.0.0"

info:
  $ref: './info/index.yaml'

servers:
  - url: http://localhost:8013/
  - url: http://localhost:8010/

components:
  schemas:
    Pet:
      $ref: "./schemas/Pet.yaml"
    Pets:
      $ref: "./schemas/Pets.yaml"
    Error:
      $ref: "./schemas/Error.yaml"

paths:
  /pets:
    $ref: "./paths/pets.yaml"
  /pets/{petId}:
    $ref: "./paths/pet.yaml"
