=begin
Swagger Petstore

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end

class InitTables < ActiveRecord::Migration
  def change
    create_table "error".pluralize.to_sym, id: false do |t|
      t.integer :code
      t.string :message

      t.timestamps
    end

    create_table "pet".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :name
      t.string :tag
      t.string :status

      t.timestamps
    end

  end
end
